AWSTemplateFormatVersion: 2010-09-09
Description: Creates Secrets Manager

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - tst
      - ppd
      - prd
    Description: Environments

  OrgName:
    Type: String
    Default: avx
    Description: 3 digit ID of the organization this belongs to

  RequiredBillingTag:
    Type: String
    Default: AVANTAX_ENVIRONMENT
    Description: Required tag for cost tracking

  ProjectName:
    Type: String
    AllowedValues:
      - cp-automation
    Description: The name of the project - Match with repo name
  
  SecretDescription:
    Type: String
    Default: Secrets for the cp-automation
    Description: The purpose of this secret

Resources:
  SecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Ref SecretDescription
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sa"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Name: !Sub avx-${ProjectName}
      Tags:
        - Key: Name
          Value: !Sub avx-${Env}-secrets-${ProjectName}
        - Key: !Ref RequiredBillingTag
          Value: !Ref Env
        - Key: Environment
          Value: !Ref Env
        - Key: Organization
          Value: !Ref OrgName

Outputs:
  AptClientportalSecretArn:
    Description: The ARN of SecretsManager
    Value: !Ref SecretsManager
