AWSTemplateFormatVersion: 2010-09-09
Description: Creates ECR Repository

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - tst
      - ppd
      - prd
    Description: Environments

  OrgName:
    Type: String
    Default: avx
    Description: 3 digit ID of the organization this belongs to

  RequiredBillingTag:
    Type: String
    Default: AVANTAX_ENVIRONMENT
    Description: Required tag for cost tracking

  ProjectName:
    Type: String
    AllowedValues:
      - cp-automation
    Description: The name of the project - Match with repo name

Mappings:
  ECR:
    avx:
      LifecyclePolicyText: |
        {
          "rules" : [
            {
              "rulePriority" : 1,
              "description" : "Expire images older than 3 days",
              "selection" : {
                "tagStatus" : "untagged",
                "countType" : "sinceImagePushed",
                "countUnit" : "days",
                "countNumber" : 3
              },
              "action" : {
                "type" : "expire"
              }
            }
          ]
        }

Conditions:
  isPRD: !Equals [ !Ref 'Env', 'prd']

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub avx-docker-repo-${ProjectName}
      LifecyclePolicy:
        LifecyclePolicyText: !FindInMap [ECR, avx, LifecyclePolicyText]
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            !If
              - isPRD
              - 
                AWS:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/avantax-devops-role
                  - !Sub arn:aws:iam::${AWS::AccountId}:user/GitHubActionsSvcAcct
                Service:
                  - codebuild.amazonaws.com
              -
                AWS:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/avantax-devops-role
                  - !Sub arn:aws:iam::${AWS::AccountId}:user/GitHubActionsSvcAcct
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/contractor-devops-role
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/avx-dev-regbi
                Service:
                  - codebuild.amazonaws.com
          Action:
          - ecr:BatchCheckLayerAvailability
          - ecr:BatchGetImage
          - ecr:CompleteLayerUpload
          - ecr:GetDownloadUrlForLayer
          - ecr:InitiateLayerUpload
          - ecr:PutImage
          - ecr:UploadLayerPart
      Tags:
        - Key: Name
          Value: !Sub avx-${Env}-ecr-${ProjectName}
        - Key: !Ref RequiredBillingTag
          Value: !Ref Env
        - Key: Environment
          Value: !Ref Env
        - Key: Organization
          Value: !Ref OrgName

Outputs:
  ECRArn:
    Description: The ARN of ECR
    Value: !GetAtt ECRRepository.Arn
